## ## keep in sync with gradle.properties in root ## ##

#Kotlin
kotlin.code.style=official
org.jetbrains.dokka.experimental.gradle.pluginMode=V2Enabled
#Android
android.useAndroidX=true

# Gradle
# make sure this stays harmonized with other kaluga projects for daemon reuse
org.gradle.jvmargs=-Xmx10g -Xms256m -XX:MaxMetaspaceSize=800m -XX:+UseParallelGC -Dfile.encoding=UTF-8
org.gradle.parallel=true

#MPP
kotlin.mpp.enableCInteropCommonization=true
