steps:
  - name: 'gcr.io/$PROJECT_ID/android:29'
    id: assemble
    args: ["./gradlew", "assemble"]
    env:
      - 'TERM=dumb'
      - 'GRADLE_USER_HOME=/workspace/gradle_home'
      - 'KONAN_DATA_DIR=/workspace/konan'
      - 'JAVA_TOOL_OPTIONS="-Xmx3g"'
      - 'GRADLE_OPTS="-Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.workers.max=8 -Dkotlin.incremental=false"'
      - 'BRANCH_NAME=$BRANCH_NAME'

  - name: 'gcr.io/$PROJECT_ID/android:29'
    id: check
    args: ["./gradlew", "check"]
    env:
      - 'TERM=dumb'
      # can only use one gradle home concurrently
      - 'GRADLE_USER_HOME=/workspace/gradle_home_check'
      - 'KONAN_DATA_DIR=/workspace/konan'
      - 'JAVA_TOOL_OPTIONS="-Xmx3g"'
      - 'GRADLE_OPTS="-Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.workers.max=8 -Dkotlin.incremental=false"'
      - 'BRANCH_NAME=$BRANCH_NAME'
    waitFor:
      - assemble
  - name: 'gcr.io/$PROJECT_ID/android:29'
    id: compileExampleAndroidUsingModules
    args: ["../../../gradlew", "--stacktrace", "-x",  "compileKotlinIosx64", "assemble"]
    env:
      - 'GRADLE_USER_HOME=/workspace/gradle_home_example_modules'
      - 'KONAN_DATA_DIR=/workspace/konan'
      - 'TERM=dumb'
      - 'JAVA_TOOL_OPTIONS="-Xmx3g"'
      - 'GRADLE_OPTS="-Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.workers.max=8 -Dkotlin.incremental=false"'
      - 'BRANCH_NAME=$BRANCH_NAME'
      - 'EXAMPLE_EMBEDDING_METHOD="maven"'
    dir: "example/ios/Supporting Files"
    waitFor:
      - check

  - name: 'gcr.io/$PROJECT_ID/android:29'
    id: localPublish
    args: ["./gradlew", "--stacktrace", "-Dmaven.repo.local=/workspace/m2", "publishToMavenLocal"]
    env:
      - 'GRADLE_USER_HOME=/workspace/gradle_home'
      - 'KONAN_DATA_DIR=/workspace/konan'
      - 'TERM=dumb'
      - 'JAVA_TOOL_OPTIONS="-Xmx3g"'
      - 'GRADLE_OPTS="-Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.workers.max=8 -Dkotlin.incremental=false"'
      - 'BRANCH_NAME=$BRANCH_NAME'
    waitFor:
      - assemble

  - name: 'gcr.io/$PROJECT_ID/android:29'
    id: compileExampleAndroidUsingM2
    args: ["../../../gradlew", "--stacktrace", "--project-cache-dir=gradle_example_project_m2","-Dmaven.repo.local=/workspace/m2", "-x",  "compileKotlinIosx64", "assemble", ]
    env:
      - 'GRADLE_USER_HOME=/workspace/gradle_home_example_m2'
      - 'KONAN_DATA_DIR=/workspace/konan'
      - 'TERM=dumb'
      - 'JAVA_TOOL_OPTIONS="-Xmx3g"'
      - 'GRADLE_OPTS="-Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.workers.max=8 -Dkotlin.incremental=false"'
      - 'BRANCH_NAME=$BRANCH_NAME'
      - 'EXAMPLE_EMBEDDING_METHOD="composite"'
    dir: "example/ios/Supporting Files"
    waitFor:
        - localPublish
        - compileExampleAndroidUsingModules

timeout: 3000s
options:
  machineType: 'N1_HIGHCPU_8'

# In future we have to save the build cache for faster builds:
#    volumes:
#      - name: 'build_cache'
#        path: '/build_cache'
#  - name: 'gcr.io/$PROJECT_ID/tar'
#    id: compress_cache
#    args: ['cpvzf', '/build_cache/cache.tgz', '-C', '/build_cache', '/build_cache/.gradle']
#    waitFor: ['build']
#    volumes:
#      - name: 'build_cache'
#        path: '/build_cache'
