## ## keep in sync with gradle.properties in [example/ios/Supporting Files] ##

#Kotlin
kotlin.code.style=official
kotlin.mpp.stability.nowarn=true
org.jetbrains.dokka.experimental.gradle.pluginMode=V2Enabled

#Android
android.useAndroidX=true
android.nonTransitiveRClass=true

# Gradle
# make sure this stays harmonized with other kaluga projects for daemon reuse
org.gradle.jvmargs=-Xmx13g -Xms256m -XX:MaxMetaspaceSize=1536m -XX:+UseParallelGC -Dfile.encoding=UTF-8
org.gradle.parallel=true
# not possible yet for kaluga
# org.gradle.configuration-cache=true

#MPP
kotlin.mpp.enableCInteropCommonization=true
kotlin.incremental.native=false
kotlin.suppressGradlePluginWarnings=TestApiDependencyWarning

#Atomicfu
kotlinx.atomicfu.enableJvmIrTransformation=true
kotlinx.atomicfu.enableNativeIrTransformation=true
kotlinx.atomicfu.enableJsIrTransformation=true

