## ## keep in sync with gradle.properties in [example/ios/Supporting Files] ##

#Kotlin
kotlin.code.style=official
kotlin.mpp.stability.nowarn=true
org.jetbrains.dokka.experimental.gradle.pluginMode=V2Enabled

#Android
android.useAndroidX=true
android.nonTransitiveRClass=true

# Gradle
# make sure this stays harmonized with other kaluga projects for daemon reuse
org.gradle.jvmargs=-Xmx12g -Xms4g -XX:MaxMetaspaceSize=1536m -XX:ReservedCodeCacheSize=512m
org.gradle.parallel=true
# not possible yet for kaluga
# org.gradle.configuration-cache=true

#MPP
kotlin.mpp.enableCInteropCommonization=true
kotlin.incremental.native=true
kotlin.suppressGradlePluginWarnings=TestApiDependencyWarning

#Atomicfu
kotlinx.atomicfu.enableJvmIrTransformation=true
kotlinx.atomicfu.enableNativeIrTransformation=true
kotlinx.atomicfu.enableJsIrTransformation=true


# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
