/*
 Copyright 2026 Splendo Consulting B.V. The Netherlands

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

 */

package com.splendo.kaluga.bluetooth.externalsource

import com.splendo.kaluga.base.test.BaseTest
import com.splendo.kaluga.base.test.testRunBlocking
import com.splendo.kaluga.bluetooth.CharacteristicProperty
import com.splendo.kaluga.bluetooth.serialization.BluetoothFormat
import com.splendo.kaluga.bluetooth.test.ConnectedMockClient
import com.splendo.kaluga.bluetooth.test.characteristic
import com.splendo.kaluga.bluetooth.test.connectedMockClient
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.async
import kotlinx.coroutines.withTimeout
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertIs
import kotlin.test.assertNotEquals
import kotlin.time.Duration.Companion.seconds

// Validates the plugin's externalAnnotationSource() capability. ComposedDevice (this module) references ExternalService,
// whose Remote* symbols are generated by :validation:external-source-provider. Because this module marks the external
// spec as externalAnnotationSource, it resolves ExternalService for that reference but does NOT regenerate its symbols;
// the link therefore succeeds only if the provider's RemoteExternalService is reused rather than duplicated. The
// round-trip drives the generated ComposedDeviceClient against the mock stack through the external characteristic,
// proving the reused symbol is wired end-to-end. It also references RemoteOwnService.UUID, which this module DID generate
// (a non-external sibling), confirming own generation and external reuse coexist in one module.
class GeneratedExternalSourceStructureTest : BaseTest() {

    private suspend fun connect(scope: CoroutineScope): ConnectedMockClient = scope.connectedMockClient {
        uuid = RemoteExternalService.UUID
        characteristics {
            characteristic {
                uuid = RemoteExternalCharacteristic.UUID
                properties += setOf(CharacteristicProperty.Read, CharacteristicProperty.Write)
            }
        }
    }

    @Test
    fun ownAndExternalServicesAreDistinctlyGenerated() {
        // Referencing both UUIDs proves the external symbol (from the provider) and the own symbol (generated here) both
        // resolve and link.
        assertNotEquals(RemoteExternalService.UUID, RemoteOwnService.UUID)
    }

    @Test
    fun readExternalServiceThroughComposedClient() = testRunBlocking {
        withTimeout(5.seconds) {
            val mock = connect(this)
            try {
                // The read value the mock device returns for e101: BluetoothFormat-encoded Int 42.
                mock.characteristicWrapper(RemoteExternalService.UUID, RemoteExternalCharacteristic.UUID)
                    .updateValue(BluetoothFormat.encodeToByteArray(BluetoothFormat.serializer<Int>(), 42))

                val client = ComposedDeviceClient.bluetoothSnapshot(mock.client, mock.identifier)

                val read = async { client.externalService.externalCharacteristic.readLevel() }
                mock.pump()
                val success = assertIs<ExternalCharacteristicReadResponse.Success>(read.await())
                assertEquals(42, success.response)
            } finally {
                mock.close()
            }
        }
    }
}
